const SIGNATURE = '// generated by genversion'

exports.SIGNATURE = SIGNATURE

exports.createContent = (version, opts) => {
  // Create content for the version module
  //
  // Parameters:
  //   version: string, version tag
  //   opts: optional object with optional properties:
  //     useSemicolon:
  //       boolean. True to use semicolons in generated code
  //     useEs6Syntax:
  //       boolean. True to use ES6 export syntax in generated code
  //     useStrict:
  //       boolean. Add the 'use strict' header
  //
  // Return:
  //   string. The version module contents.
  //
  let content = SIGNATURE + '\n'

  // In some cases 'use strict' is required in the file
  // Can have comments before, but must be first statement
  if (opts.useStrict) {
    if (opts.useSemicolon) {
      content += '\'use strict\';\n\n'
    } else {
      content += '\'use strict\'\n\n'
    }
  }

  if (opts.useEs6Syntax) {
    content += 'export const version'
  } else {
    content += 'module.exports'
  }

  content += ' = \'' + version + '\''

  // Some code styles use semicolons, others do not.
  if (opts.useSemicolon) {
    content += ';\n'
  } else {
    content += '\n'
  }

  return content
}
